title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
baseurl: "/den-docs"
url: "https://denis-kol4ev.github.io"

theme: just-the-docs
#theme: minima
#url: https://just-the-docs.github.io
#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template